### ISSUE TITLE
A couple of suggestions...

### ISSUE THREAD

**Issue by kevinkuszyk** [oledid-js/cucumber-json-to-teamcity#4]
First up thanks for a useful lib.

Based on our usage over the past couple of months, I have a couple of suggested enhancements:

- [ ] Add a option to only show scenarios in the team city output.
- [X] If a step or scenario is skipped, show it as ignored in the team city output.
- [ ] Update to latest node.js LTS

If you agree, I'll make a start on a PR.

**Comment by oledid** [comment]
Hi @kevinkuszyk 

Sounds good. Feel free to start on a PR. I'm probably not going to do much before jan 2., but I will look at it when I get the chance.

**Comment by kevinkuszyk** [comment]
Thanks.  Today is my last day in the office until 3rd Jan.

I'll get something over to you in the new year.

**Comment by kevinkuszyk** [comment]
I'm having some trouble with the `skipped` status.  I can't make a scenario set it's status as `skipped` in Cucumber 1.x or 2.x, so I think they must have made a change in 3.x.

How would you feel about dropping support for 1.x and 2.x and only supporting 3.x?

**Comment by oledid** [comment]
@kevinkuszyk  Sure, we can create a new major version.

**Comment by oledid** [comment]
@kevinkuszyk are you finding a solution to your problems?

If the json output is deprecated ( cucumber/cucumber-js/issues/1007 ) it would probably be better to write a tap-formatter for cucumber-js and use [smockle/tap-teamcity](https://github.com/smockle/tap-teamcity) ... or wait, that project is archived :)

Better to have two plugins at least, one cucumber-js-plugin for formatting the test results to a common format, and one to use that common format in teamcity.

If someone decides to re-implement the json format, this repository will still be relevant. But the cucumber-js json is not exactly a "common format".

**Comment by kevinkuszyk** [comment]
> @kevinkuszyk are you finding a solution to your problems?

Yes, we've been running a local build based off #5 for the past couple of weeks.  It's running well for us.  If you can publish that to npm we'll switch back to the official version.

> If the json output is deprecated ( cucumber/cucumber-js#1007 ) it would probably be better to write a tap-formatter for cucumber-js and use smockle/tap-teamcity ... or wait, that project is archived :)

Yes, this is not ideal.  

I've been experimenting with @bingnz's [cucumber-teamcity-formatter](https://github.com/bingnz/cucumber-teamcity-formatter).  It uses the new event emitter which means each scenario is mapped to a test in team city.  Unfortunately it also lacks support for skipped tests (see bingnz/cucumber-teamcity-formatter#2), and I've been having trouble getting that working.

> If someone decides to re-implement the json format, this repository will still be relevant. But the cucumber-js json is not exactly a "common format".

Agreed.  I'm afraid I think it might be time to move on.

Once again, thanks for a useful lib.  If you woudn't mind pushing a new version to npm, we'll use that until we are able to move over to something based on the event emitter.

Best,
Kevin.

**Comment by oledid** [comment]
Closed because of probable deprecation.
